version: "3.3"
services:
  react-app:
    build:
      context: ./app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api:/var/www/api
    depends_on:
      - react-app

  php-api:
    build:
      context: ./api
    volumes:
      - ./api:/var/www/api:ro
    ports:
      - "9000:9000"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: exemplo-cris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
