name: Docker Image CI

on:
  push:
    branches: [ "prod" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version from package.json
        id: extract_version
        run: |
          VERSION_TAG=$(jq -r .version app/package.json)
          echo "version_tag=$VERSION_TAG" >> "$GITHUB_OUTPUT"

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        uses: docker/build-push-action@v4
        with:
          context: ./app
          # List of external cache sources for buildx (e.g., user/app:cache, type=local,src=path/to/dir)
          cache-from: type=local,src=/tmp/.buildx-cache
          # List of cache export destinations for buildx (e.g., user/app:cache, type=local,dest=path/to/dir)
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          # Path to the Dockerfile
          file: ./app/Dockerfile
          # Push is a shorthand for --output=type=registry
          push: true
          # List of tags
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/example_docker_react_app:${{ steps.extract_version.outputs.version_tag }}
            ${{ secrets.DOCKER_USERNAME }}/example_docker_react_app:latest

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache